### ISSUE TITLE
Handle deprecated OOB OAuth flow

### ISSUE THREAD

**Issue by rebkwok** [ebmdatalab/datalab-pandas#32]
OOB OAuth authentication [has been deprecated](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html?m=1#disallowed-oob) and will be disabled on 1st May 2023.

This means that the prompt to go to a URL to get a token to copy/paste to authenticate with big query will no longer work; if pandas is upgraded past 1.5.0, it will default to using the [local webserver flow](https://pandas.pydata.org/docs/reference/api/pandas.read_gbq.html), but with the very old versions of pandas that are allowed in this package (>=0.24) it will default to using the console flow.

Any notebooks using this package, or the [datalab-jupyter](https://github.com/ebmdatalab/datalab-jupyter) image which depends on it (or pandas-gpq directly) will need to upgrade to a newer form of authentication.  For notebooks, it will need to load credentials from the environment; these will need to be kept secure
https://googleapis.dev/python/pandas-gbq/latest/howto/authentication.html

See this thread: https://bennettoxford.slack.com/archives/C31D62X5X/p1681815645435669

**Comment by inglesp** [comment]
I timeboxed a day for this and have got nowhere.  I'm confused by Google's auth workflows, am stuck in dependency hell, and don't have anything like a coherent strategy for making progress.

The good news is that notebooks that use `ebmdatalab.bq.cached_read` continue to work (with a warning) even though we're after 1st May.

**Comment by inglesp** [comment]
This was addressed in #35.  However, we can't update the docker images because of https://github.com/ebmdatalab/datalab-jupyter/issues/8.

Users can work around this, by changing:

```df = bq.cached_read(sql, ...)```

to:

```df = bq.cached_read(sql, ..., auth_local_webserver=True)```

See [this Slack thread](https://bennettoxford.slack.com/archives/C02HJTL065A/p1684229808586159?thread_ts=1682338456.022299&cid=C02HJTL065A).

**Comment by sebbacon** [comment]
This is still not working, per Slack thread linked to above.

**Comment by sebbacon** [comment]
Error reported by @richiecroker:

![image](https://github.com/ebmdatalab/datalab-pandas/assets/211271/540a7c5c-0a1a-4b24-a45f-402b4d85ed58)
